---

version: '3'
services:
    traefik:
        image: bearstech/traefik-dev:2.0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - web
        expose:
            - 80

    web:
        image: bearstech/nginx:${DEBIAN_VERSION}
        volumes:
            - ./index.html:/var/www/html/index.html
            - ./nginx_mirror.conf:/etc/nginx/sites-enabled/mirror
            - ./data/log:/var/log/nginx
        expose:
            - '8000'
        depends_on:
            - mirror
        labels:
            traefik.enable: 'true'
            traefik.http.routers.nginxWebRouter.rule: >
                Host(`traefik-nginx`, `glasses`)

    mirror:
        image: bearstech/http-mirror

    client:
        image: bearstech/debian:buster
        volumes:
            - ../bin/goss:/usr/bin/goss
            - ../tests_nginx:/goss
            - ./data/log:/data/log
            - ./traefik_hosts:/etc/hosts
        working_dir: /goss
        restart: "no"
        depends_on:
            - web
            - traefik
