---

version: '3'
services:
    traefik:
        image: bearstech/traefik-dev
        links:
            - web

    web:
        image: bearstech/nginx
        volumes:
            - ../tests_nginx/index.html:/var/www/html/index.html
        ports:
            - '8000:8000'

    client:
        image: bearstech/debian:stretch
        volumes:
            - ../bin/goss:/usr/bin/goss
            - ../tests_nginx:/goss
        working_dir: /goss
        links:
            - web
            - traefik
