---

version: '3'
services:
    traefik:
        image: bearstech/traefik-dev
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - web

    web:
        image: bearstech/nginx
        volumes:
            - ./index.html:/var/www/html/index.html
            - ./nginx_mirror.conf:/etc/nginx/sites-enabled/mirror
        ports:
            - '8000'
        links:
            - mirror
        labels:
            traefik.frontend.rule: Host:traefik,glasses

    mirror:
        image: bearstech/http-mirror

    client:
        image: bearstech/debian:stretch
        volumes:
            - ../bin/goss:/usr/bin/goss
            - ../tests_nginx:/goss
        working_dir: /goss
        links:
            - web
            - traefik
            - traefik:glasses
