---

version: '3'
services:
    traefik:
        image: bearstech/traefik-dev:2.0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - web
        ports:
            - 80

    web:
        image: bearstech/nginx:latest
        volumes:
            - ./index.html:/var/www/html/index.html
            - ./nginx_mirror.conf:/etc/nginx/sites-enabled/mirror
            - ./data/log:/var/log/nginx
        ports:
            - '8000'
        links:
            - mirror
        labels:
            traefik.http.routers.nginxRouter.rule: Host(`traefik`, `glasses`)

    mirror:
        image: bearstech/http-mirror

    client:
        image: bearstech/debian:stretch
        volumes:
            - ../bin/goss:/usr/bin/goss
            - ../tests_nginx:/goss
            - ./data/log:/data/log
        working_dir: /goss
        links:
            - web
            - traefik
            - traefik:glasses
